default: &default
  adapter: mysql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: rails_blog_development

test:
  <<: *default
  database: rails_blog_test

production:
  <<: *default
  database: rails_blog_production
  username: blogger
  password: <%= ENV['RAILS_BLOG_DATABASE_PASSWORD'] %>
